language: java
sudo: false
dist: trusty
jdk:
- oraclejdk11
- oraclejdk14
before_install:
  - chmod +x gradle/wrapper/gradle-wrapper.jar
script:
  - ./gradlew build
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/