name: Java CI

on:
  workflow_call:
    inputs:
      jdk_version:
        description: "JDK version to build."
        type: string
        required: false
        default: '21'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: ${{ inputs.jdk_version }}
          architecture: x64
          cache: gradle
      - name: 🏭 Build with Gradle
        run: ./gradlew build --no-daemon
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: cadibot-distribution
          path: build/distributions/Cadibot.zip
          retention-days: 1
